name: "topic_modeling_onnx_only"
platform: "onnxruntime_onnx"
max_batch_size: 250
instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]
input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ -1 ]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [ -1 ]
  }
]
output [
  {
    name: "output_0"
    data_type: TYPE_FP32
    dims: [ -1, 768 ]
  },
  {
    name: "output_1"
    data_type: TYPE_FP32
    dims: [ 768 ]
  }
]
