name: "postprocess"
backend: "python"
max_batch_size: 250
instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]
parameters: {
  key: "FORCE_CPU_ONLY_INPUT_TENSORS"
  value: {
    string_value:"no"
  }
}
input [
  {
    name: "output_0"
    data_type: TYPE_FP32
    dims: [ -1, 768 ]
  },
  {
    name: "output_1"
    data_type: TYPE_FP32
    dims: [ 768 ]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [ -1 ]
  }
]
output [
  {
    name: "OUTPUT1"
    data_type: TYPE_FP32
    dims: [ 768 ]
  }
]